# isort is used for autoformatting Python code
#
# ref: https://pycqa.github.io/isort/
#
[tool.isort]
profile = "black"


# black is used for autoformatting Python code
#
# ref: https://black.readthedocs.io/en/stable/
#
[tool.black]
skip-string-normalization = true
target_version = [
    "py38",
    "py39",
    "py310",
    "py311",
]


# pytest is used for running Python based tests
#
# ref: https://docs.pytest.org/en/stable/
#
[tool.pytest.ini_options]
addopts = "--verbose --color=yes --durations=10 --maxfail=1"
asyncio_mode = "auto"
testpaths = ["tests"]
# These markers are registered to avoid warnings triggered by importing from
# jupyterhub.tests.test_api.
markers = [
    "role",
    "user",
    "slow",
    "group",
    "services",
]
